#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Twitter Bot written by Joseph Weiner for hackMarist 2016
#Inspired in part by LACUNY "Build a twitter bot day 2015"
#Credit for any directly copied code goes to the CUNY committe, however directly copied code is scarce as most things have been changed.

# This bot tweets a text file line by line
#Using a sleep method it rests for 30 seconds before completing the for loop

# This Twitter Bot takes from a generated text of the Marist Student Handbook and Code Of Conduct
#The aforementioned text file was generated by me for this specific project.
#It can be downloaded in the Git repository, however, I'm not sure what its use would be for a non-Marist Student


# Housekeeping: do not edit
import tweepy, time
from credentials import *
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_SECRET)
api = tweepy.API(auth)


# What the bot will tweet

filename = open('studentconduct.txt','r')
tweettext = filename.readlines()
filename.close()

for line in tweettext[0:3535]: #Will write all of the lines
    api.update_status(line)
    print line
    time.sleep(30) # Sleep for 30 seconds

print "Complete!"

# To quit early: CTRL+C and wait a few seconds
